[build]
rustflags = [
    "-C", "link-arg=-s",
    "-C", "target-cpu=native",
    "-C", "embed-bitcode=yes",
    "-Z", "share-generics=y",
    "-Z", "location-detail=none",
]

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "link-arg=-s",
    "-C", "target-cpu=native",
    "-C", "embed-bitcode=yes",
    "-Z", "share-generics=y",
    "-Z", "location-detail=none",
]